version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg:/var/lib/postgresql/data
    restart: unless-stopped

  ingest:
    build: ./ingest-api
    env_file: .env
    ports: ["8001:8001"]
    depends_on: [db]
    restart: unless-stopped

volumes:
  pg: